name: CI
on: [push]
jobs:
  eslint:
    name: Format & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i
      - name: Run Build
        run: npm run build
      - name: Run Prettier
        run: npm run format
      - name: Run Test
        run: npm test
